### ISSUE TITLE
can not add element into empty array

### ISSUE THREAD

**Issue by Red-C** [krispo/simplifr#6]
export function add(data, path, obj, dilimiter){
  dilimiter = dilimiter || defaults().dilimiter;
  var node = data[path];

  if (typeof node === 'undefined' || typeof node === 'null')
    return data;

  if (node.type === 'array') {
    var max = Math.max.apply(null, node.childs);
    if (!isArray(obj)) obj = [obj];
    obj.forEach(function(d){
      node.childs.push(++max);
      simplifyNode(data, path + dilimiter + max, d, dilimiter);
    });
  }

  else if (node.type === 'object') {
    var keys = Object.keys(obj);
    keys.forEach(function(key){
      if (node.childs.indexOf(key) > -1) return;
      node.childs.push(key);
      simplifyNode(data, path + dilimiter + key, obj[key], dilimiter);
    });
  }

  return data;
}

Math.max.apply(null, []) returns -infinity.

**Comment by krispo** [comment]
Thanks! I've fixed it (v0.2.1).
